Update part4b.md
I got this error ("TypeError: Note.findByIdAndRemove is not a function," ) while deleteing a note with mongoose v 8.
I think this is because the "findByIdAndRemove" function has been deprecated and "findByIdAndDelete" is the alternative.